In [1]:
import pandas as pd

In [5]:
data = pd.read_csv("../Data/Vehicle Fuel Economy Data.csv")

C:\Users\aje0v\AppData\Local\Temp\ipykernel_22656\1071883395.py:1: DtypeWarning: Columns (73,75) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("../Data/Vehicle Fuel Economy Data.csv")

In [6]:
display(data)

,Year,Manufacturer,Model,barrels08,barrelsA08,charge240,city08,city08U,cityA08,cityA08U,...,mfrCode,c240Dscr,charge240b,c240bDscr,createdOn,modifiedOn,startStop,phevCity,phevHwy,phevComb
0,2017,BMW,M6 Coupe,17.500588,0.0,0.0,15.0,14.0,0.0,0.0,...,BMX,NaN,0.0,NaN,04-04-2016,09-09-2016,Y,0.0,0.0,0.0
1,2017,BMW,X3 sDrive28i,12.396250,0.0,0.0,21.0,21.0,0.0,0.0,...,BMX,NaN,0.0,NaN,04-04-2016,22-11-2016,Y,0.0,0.0,0.0
2,2016,Infiniti,Q50S Red Sport,13.523182,0.0,0.0,20.0,19.0,0.0,0.0,...,NSX,NaN,0.0,NaN,04-04-2016,26-09-2016,N,0.0,0.0,0.0
3,2017,MINI,John Cooper Works Convertible,11.018889,0.0,0.0,24.0,23.0,0.0,0.0,...,BMX,NaN,0.0,NaN,12-04-2016,16-09-2016,Y,0.0,0.0,0.0
4,2017,Kia,Sedona SX,14.167143,0.0,0.0,18.0,18.0,0.0,0.0,...,KMX,NaN,0.0,NaN,12-04-2016,02-12-2016,N,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46181,1993,Plymouth,Sundance/Duster,12.935217,0.0,0.0,21.0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,01-01-2013,01-01-2013,NaN,0.0,0.0,0.0
46182,1993,Pontiac,Grand Am,14.167143,0.0,0.0,18.0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,01-01-2013,01-01-2013,NaN,0.0,0.0,0.0
46183,1993,Saab,900,14.167143,0.0,0.0,18.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46184,1993,Subaru,Legacy,13.523182,0.0,0.0,19.0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,01-01-2013,01-01-2013,NaN,0.0,0.0,0.0
46185,1993,Subaru,Legacy AWD,14.167143,0.0,0.0,18.0,0.0,0.0,0.0,...,NaN,NaN,0.0,NaN,01-01-2013,01-01-2013,NaN,0.0,0.0,0.0

In [16]:
columns_to_keep = ['Year','Manufacturer','Model', 'charge240','feScore', 'fuelCost08', 'fuelType1', 'VClass']

In [17]:
df_clean = data[columns_to_keep]

In [18]:
df_clean

,Year,Manufacturer,Model,charge240,feScore,fuelCost08,fuelType1,VClass
0,2017,BMW,M6 Coupe,0.0,3.0,3850.0,Premium Gasoline,Subcompact Cars
1,2017,BMW,X3 sDrive28i,0.0,5.0,2700.0,Premium Gasoline,Small Sport Utility Vehicle 2WD
2,2016,Infiniti,Q50S Red Sport,0.0,5.0,2950.0,Premium Gasoline,Midsize Cars
3,2017,MINI,John Cooper Works Convertible,0.0,6.0,2400.0,Premium Gasoline,Minicompact Cars
4,2017,Kia,Sedona SX,0.0,4.0,2550.0,Regular Gasoline,Minivan - 2WD
...,...,...,...,...,...,...,...,...
46181,1993,Plymouth,Sundance/Duster,0.0,-1.0,2300.0,Regular Gasoline,Compact Cars
46182,1993,Pontiac,Grand Am,0.0,-1.0,2550.0,Regular Gasoline,Compact Cars
46183,1993,Saab,900,0.0,NaN,NaN,NaN,NaN
46184,1993,Subaru,Legacy,0.0,-1.0,2400.0,Regular Gasoline,Compact Cars
46185,1993,Subaru,Legacy AWD,0.0,-1.0,2550.0,Regular Gasoline,Compact Cars

In [21]:
Clases = ['Subcompact Cars','Compact Cars','Minicompact Cars']

# Filtrar el DataFrame por los modelos necesarios
filtered_df = df_clean[df_clean['VClass'].isin(Clases)]

In [23]:
filtered_df

,Year,Manufacturer,Model,charge240,feScore,fuelCost08,fuelType1,VClass
0,2017,BMW,M6 Coupe,0.0,3.0,3850.0,Premium Gasoline,Subcompact Cars
3,2017,MINI,John Cooper Works Convertible,0.0,6.0,2400.0,Premium Gasoline,Minicompact Cars
10,2017,BMW,650i xDrive Convertible,0.0,3.0,3650.0,Premium Gasoline,Subcompact Cars
11,2017,Maserati,GranTurismo,0.0,2.0,4100.0,Premium Gasoline,Subcompact Cars
17,2017,Kia,Rio,0.0,7.0,1700.0,Regular Gasoline,Compact Cars
...,...,...,...,...,...,...,...,...
46179,1993,Oldsmobile,Achieva,0.0,-1.0,2200.0,Regular Gasoline,Compact Cars
46181,1993,Plymouth,Sundance/Duster,0.0,-1.0,2300.0,Regular Gasoline,Compact Cars
46182,1993,Pontiac,Grand Am,0.0,-1.0,2550.0,Regular Gasoline,Compact Cars
46184,1993,Subaru,Legacy,0.0,-1.0,2400.0,Regular Gasoline,Compact Cars
46185,1993,Subaru,Legacy AWD,0.0,-1.0,2550.0,Regular Gasoline,Compact Cars

In [24]:
filtered_df.to_csv("../Data/Data Procesada/Vehicle Fuel Economy clean.csv", index= False)